"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

// Определяем все поддерживаемые языки
type Language =
  | "en" // английский
  | "ru" // русский
  | "zh" // китайский
  | "ar" // арабский
  | "ko" // корейский
  | "fa" // фарси
  | "ja" // японский
  | "fr" // французский
  | "de" // немецкий
  | "es" // испанский
  | "it" // итальянский
  | "pt" // бразильский португальский
  | "hi" // хинди

// Информация о языке для отображения в интерфейсе
interface LanguageInfo {
  code: Language
  name: string
  nativeName: string
  direction: "ltr" | "rtl"
}

// Массив с информацией о всех поддерживаемых языках
export const languages: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English", direction: "ltr" },
  { code: "ru", name: "Russian", nativeName: "Русский", direction: "ltr" },
  { code: "zh", name: "Chinese", nativeName: "中文", direction: "ltr" },
  { code: "ar", name: "Arabic", nativeName: "العربية", direction: "rtl" },
  { code: "ko", name: "Korean", nativeName: "한국어", direction: "ltr" },
  { code: "fa", name: "Persian", nativeName: "فارسی", direction: "rtl" },
  { code: "ja", name: "Japanese", nativeName: "日本語", direction: "ltr" },
  { code: "fr", name: "French", nativeName: "Français", direction: "ltr" },
  { code: "de", name: "German", nativeName: "Deutsch", direction: "ltr" },
  { code: "es", name: "Spanish", nativeName: "Español", direction: "ltr" },
  { code: "it", name: "Italian", nativeName: "Italiano", direction: "ltr" },
  { code: "pt", name: "Portuguese (Brazil)", nativeName: "Português", direction: "ltr" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", direction: "ltr" },
]

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  getLanguageInfo: (code: Language) => LanguageInfo
  languages: LanguageInfo[]
}

// Базовые переводы для всех языков
const translations: Record<string, Record<Language, string>> = {
  // AML/KYC Policy
  "aml.title": {
    en: "AML/KYC Policy",
    ru: "Политика AML/KYC",
    zh: "反洗钱/了解您的客户政策",
    ar: "سياسة مكافحة غسل الأموال/اعرف عميلك",
    ko: "자금세탁방지/고객확인제도 정책",
    fa: "سیاست مبارزه با پولشویی/شناخت مشتری",
    ja: "マネーロンダリング防止/顧客確認ポリシー",
    fr: "Politique LAB/KYC",
    de: "AML/KYC-Richtlinie",
    es: "Política AML/KYC",
    it: "Politica AML/KYC",
    pt: "Política AML/KYC",
    hi: "एएमएल/केवाईसी नीति",
  },
  "aml.subtitle": {
    en: "Last updated: May 10, 2025",
    ru: "Последнее обновление: 10 мая 2025",
    zh: "关于反洗钱政策和了解您的客户程序的信息",
    ar: "معلومات حول سياسة مكافحة غسل الأموال وإجراءات اعرف عميلك",
    ko: "자금세탁방지 정책 및 고객확인제도 절차에 관한 정보",
    fa: "اطلاعات در مورد سیاست مبارزه با پولشویی و روش‌های شناخت مشتری",
    ja: "マネーロンダリング防止ポリシーと顧客確認手続きに関する情報",
    fr: "Informations sur la politique de lutte contre le blanchiment d'argent et les procédures de connaissance du client",
    de: "Informationen zur Geldwäschebekämpfungspolitik und zu Verfahren zur Kundenidentifizierung",
    es: "Información sobre la política contra el lavado de dinero y los procedimientos de Conozca a su Cliente",
    it: "Informazioni sulla politica antiriciclaggio e sulle procedure di identificazione del cliente",
    pt: "Informações sobre a política de combate à lavagem de dinheiro e procedimentos de Conheça Seu Cliente",
    hi: "एंटी-मनी लॉन्ड्रिंग नीति और नो योर कस्टमर प्रक्रियाओं के बारे में जानकारी",
  },
  "aml.section1.title": {
    en: "Introduction",
    ru: "Введение",
    zh: "1. 介绍",
    ar: "1. مقدمة",
    ko: "1. 소개",
    fa: "1. مقدمه",
    ja: "1. はじめに",
    fr: "1. Introduction",
    de: "1. Einführung",
    es: "1. Introducción",
    it: "1. Introduzione",
    pt: "1. Introdução",
    hi: "1. परिचय",
  },
  "aml.section1.content": {
    en: "Our company is committed to preventing and detecting any forms of money laundering and terrorist financing. This policy establishes our procedures for compliance with applicable laws and regulations.",
    ru: "Наша компания стремится предотвращать и выявлять любые формы отмывания денег и финансирования терроризма. Эта политика устанавливает наши процедуры для соблюдения применимых законов и нормативных актов.",
    zh: "本反洗钱/了解您的客户政策旨在防止和减轻 Chupapi Munyanya 可能参与任何非法活动的风险。",
    ar: "تم تصميم سياسة مكافحة غسل الأموال/اعرف عميلك هذه لمنع وتخفيف المخاطر المحتملة لتورط Chupapi Munyanya في أي نوع من النشاط غير القانوني.",
    ko: "이 자금세탁방지/고객확인제도 정책은 Chupapi Munyanya가 어떤 종류의 불법 활동에 관여될 가능성을 방지하고 완화하기 위해 설계되었습니다.",
    fa: "این سیاست مبارزه با پولشویی/شناخت مشتری برای جلوگیری و کاهش خطرات احتمالی درگیر شدن Chupapi Munyanya در هر نوع فعالیت غیرقانونی طراحی شده است.",
    ja: "このAML/KYCポリシーは、Chupapi Munyanyaがあらゆる種類の違法行為に関与する可能性のあるリスクを防止し、軽減するために設計されています。",
    fr: "Cette politique LAB/KYC est conçue pour prévenir et atténuer les risques possibles que Chupapi Munyanya soit impliqué dans tout type d'activité illégale.",
    de: "Diese AML/KYC-Richtlinie soll mögliche Risiken verhindern und mindern, dass Chupapi Munyanya an illegalen Aktivitäten beteiligt ist.",
    es: "Esta Política AML/KYC está diseñada para prevenir y mitigar posibles riesgos de que Chupapi Munyanya esté involucrado en cualquier tipo de actividad ilegal.",
    it: "Questa Politica AML/KYC è progettata per prevenire e mitigare possibili rischi che Chupapi Munyanya sia coinvolto in qualsiasi tipo di attività illegale.",
    pt: "Esta Política AML/KYC foi projetada para prevenir e mitigar possíveis riscos de a Chupapi Munyanya estar envolvida em qualquer tipo de atividade ilegal.",
    hi: "यह एएमएल/केवाईसी नीति चुपापी मुन्यान्या के किसी भी प्रकार की अवैध गतिविधि में शामिल होने के संभावित जोखिमों को रोकने और कम करने के लिए डिज़ाइन की गई है।",
  },
  "aml.section2.title": {
    en: "Customer Due Diligence Procedures",
    ru: "Процедуры проверки клиентов",
    zh: "2. 验证程序",
    ar: "2. إجراءات التحقق",
    ko: "2. 확인 절차",
    fa: "2. روش‌های تأیید",
    ja: "2. 検証手続き",
    fr: "2. Procédures de vérification",
    de: "2. Verifizierungsverfahren",
    es: "2. Procedimientos de verificación",
    it: "Procedure di verifica",
    pt: "Procedimentos de verificação",
    hi: "2. सत्यापन प्रक्रियाएं",
  },
  "aml.section2.content": {
    en: "We apply the following procedures to verify the identity of our customers:",
    ru: "Мы применяем следующие процедуры для проверки личности наших клиентов:",
    zh: "Chupapi Munyanya 实施验证程序以确定其用户的身份和活动性质。身份验证按照以下规则执行：",
    ar: "تنفذ Chupapi Munyanya إجراءات التحقق لتحديد هوية مستخدميها وطبيعة أنشطتهم. يتم إجراء التحقق من الهوية وفقًا للقواعد التالية:",
    ko: "Chupapi Munyanya는 사용자의 신원과 활동 성격을 확인하기 위한 확인 절차를 구현합니다. 신원 확인은 다음 규칙에 따라 수행됩니다:",
    fa: "Chupapi Munyanya روش‌های تأیید را برای تعیین هویت کاربران خود و ماهیت فعالیت‌های آنها اجرا می‌کند. تأیید هویت مطابق با قوانین زیر انجام می‌شود:",
    ja: "Chupapi Munyanyaは、ユーザーの身元とその活動の性質を確立するための検証手続きを実施しています。身元確認は以下の規則に従って実施されます：",
    fr: "Chupapi Munyanya met en œuvre des procédures de vérification pour établir l'identité de ses utilisateurs et la nature de leurs activités. La vérification d'identité est effectuée conformément aux règles suivantes :",
    de: "Chupapi Munyanya implementiert Verifizierungsverfahren, um die Identität seiner Benutzer und die Art ihrer Aktivitäten festzustellen. Die Identitätsüberprüfung erfolgt gemäß den folgenden Regeln:",
    es: "Chupapi Munyanya implementa procedimientos de verificación para establecer la identidad de sus usuarios y la naturaleza de sus actividades. La verificación de identidad se realiza de acuerdo con las siguientes reglas:",
    it: "Chupapi Munyanya implementa procedure di verifica per stabilire l'identità dei suoi utenti e la natura delle loro attività. La verifica dell'identità viene eseguita in conformità con le seguenti regole:",
    pt: "A Chupapi Munyanya implementa procedimentos de verificação para estabelecer a identidade de seus usuários e a natureza de suas atividades. A verificação de identidade é realizada de acordo com as seguintes regras:",
    hi: "चुपापी मुन्यान्या अपने उपयोगकर्ताओं की पहचान और उनकी गतिविधियों की प्रकृति स्थापित करने के लिए सत्यापन प्रक्रियाओं को लागू करता है। पहचान सत्यापन निम्नलिखित नियमों के अनुसार किया जाता है:",
  },
  "aml.section2.list.item1": {
    en: "Identity verification using valid government-issued documents",
    ru: "Проверка личности с использованием действительных государственных документов",
    zh: "用户必须提供其全名、出生日期、地址和电话号码；",
    ar: "يجب على المستخدمين تقديم اسمهم الكامل وتاريخ الميلاد والعنوان ورقم الهاتف؛",
    ko: "사용자는 전체 이름, 생년월일, 주소 및 전화번호를 제공해야 합니다;",
    fa: "کاربران باید نام کامل، تاریخ تولد، آدرس و شماره تلفن خود را ارائه دهند؛",
    ja: "ユーザーは、氏名、生年月日、住所、電話番号を提供する必要があります；",
    fr: "Les utilisateurs doivent fournir leur nom complet, leur date de naissance, leur adresse et leur numéro de téléphone ;",
    de: "Benutzer müssen ihren vollständigen Namen, Geburtsdatum, Adresse und Telefonnummer angeben;",
    es: "Los usuarios deben proporcionar su nombre completo, fecha de nacimiento, dirección y número de teléfono;",
    it: "Gli utenti devono fornire il loro nome completo, data di nascita, indirizzo e numero di telefono;",
    pt: "Os usuários devem fornecer seu nome completo, data de nascimento, endereço e número de telefone;",
    hi: "उपयोगकर्ताओं को अपना पूरा नाम, जन्म तिथि, पता और फोन नंबर प्रदान करना होगा;",
  },
  "aml.section2.list.item2": {
    en: "Verification of residential address",
    ru: "Проверка адреса проживания",
    zh: "用户必须提供有效的政府颁发的身份证明；",
    ar: "يجب على المستخدمين تقديم هوية صادرة عن الحكومة سارية المفعول؛",
    ko: "사용자는 유효한 정부 발행 신분증을 제공해야 합니다;",
    fa: "کاربران باید یک کارت شناسایی معتبر صادر شده توسط دولت ارائه دهند؛",
    ja: "ユーザーは有効な政府発行の身分証明書を提供する必要があります；",
    fr: "Les utilisateurs doivent fournir une pièce d'identité valide délivrée par le gouvernement ;",
    de: "Benutzer müssen einen gültigen staatlich ausgestellten Ausweis vorlegen;",
    es: "Los usuarios deben proporcionar una identificación válida emitida por el gobierno;",
    it: "Gli utenti devono fornire un documento d'identità valido rilasciato dal governo;",
    pt: "Os usuários devem fornecer um documento de identidade válido emitido pelo governo;",
    hi: "उपयोगकर्ताओं को सरकार द्वारा जारी एक वैध पहचान पत्र प्रदान करना होगा;",
  },
  "aml.section2.list.item3": {
    en: "Assessment of customer risk profile",
    ru: "Оценка профиля риска клиента",
    zh: "文件必须有效且真实。",
    ar: "يجب أن تكون المستندات صالحة وأصلية.",
    ko: "문서는 유효하고 진본이어야 합니다.",
    fa: "اسناد باید معتبر و اصل باشند.",
    ja: "書類は有効かつ本物でなければなりません。",
    fr: "Les documents doivent être valides et authentiques.",
    de: "Dokumente müssen gültig und authentisch sein.",
    es: "Los documentos deben ser válidos y auténticos.",
    it: "I documenti devono essere validi e autentici.",
    pt: "Os documentos devem ser válidos e autênticos.",
    hi: "दस्तावेज़ वैध और प्रामाणिक होने चाहिए।",
  },
  "aml.section3.title": {
    en: "Transaction Monitoring",
    ru: "Мониторинг транзакций",
    zh: "3. 合规官",
    ar: "3. مسؤول الامتثال",
    ko: "3. 준법 책임자",
    fa: "3. مسئول انطباق",
    ja: "3. コンプライアンス責任者",
    fr: "3. Responsable de la conformité",
    de: "3. Compliance-Beauftragter",
    es: "3. Oficial de Cumplimiento",
    it: "Responsabile della conformità",
    pt: "Oficial de Conformidade",
    hi: "3. अनुपालन अधिकारी",
  },
  "aml.section3.content": {
    en: "We continuously monitor transactions to identify suspicious activity, including unusually large transactions, complex payment patterns, or transactions without a clear economic purpose.",
    ru: "Мы постоянно отслеживаем транзакции для выявления подозрительной активности, включая необычно крупные транзакции, сложные схемы платежей или транзакции без явной экономической цели.",
    zh: "合规官是由 Chupapi Munyanya 正式授权的人员，其职责是确保有效实施和执行反洗钱/了解您的客户政策。",
    ar: "مسؤول الامتثال هو الشخص المفوض حسب الأصول من قبل Chupapi Munyanya، والذي تتمثل مهمته في ضمان التنفيذ والإنفاذ الفعال لسياسة مكافحة غسل الأموال/اعرف عميلك.",
    ko: "준법 책임자는 Chupapi Munyanya에 의해 정식으로 승인된 사람으로, 자금세탁방지/고객확인제도 정책의 효과적인 구현 및 시행을 보장하는 임무를 맡고 있습니다.",
    fa: "مسئول انطباق فردی است که به طور رسمی توسط Chupapi Munyanya مجاز شده است و وظیفه او اطمینان از اجرا و اعمال مؤثر سیاست مبارزه با پولشویی/شناخت مشتری است.",
    ja: "コンプライアンス責任者は、Chupapi Munyanyaによって正式に承認された人物であり、AML/KYCポリシーの効果的な実施と施行を確保する義務があります。",
    fr: "Le Responsable de la conformité est la personne, dûment autorisée par Chupapi Munyanya, dont le devoir est d'assurer la mise en œuvre et l'application efficaces de la politique LAB/KYC.",
    de: "Der Compliance-Beauftragte ist die von Chupapi Munyanya ordnungsgemäß autorisierte Person, deren Aufgabe es ist, die wirksame Umsetzung und Durchsetzung der AML/KYC-Richtlinie sicherzustellen.",
    es: "El Oficial de Cumplimiento es la persona, debidamente autorizada por Chupapi Munyanya, cuyo deber es garantizar la implementación y el cumplimiento efectivos de la Política AML/KYC.",
    it: "Il Responsabile della conformità è la persona, debitamente autorizzata da Chupapi Munyanya, il cui compito è garantire l'efficace attuazione e applicazione della Politica AML/KYC.",
    pt: "O Oficial de Conformidade é a pessoa, devidamente autorizada pela Chupapi Munyanya, cujo dever é garantir a implementação e aplicação eficazes da Política AML/KYC.",
    hi: "अनुपालन अधिकारी वह व्यक्ति है, जिसे चुपापी मुन्यान्या द्वारा विधिवत अधिकृत किया गया है, जिसका कर्तव्य एएमएल/केवाईसी नीति के प्रभावी कार्यान्वयन और प्रवर्तन को सुनिश्चित करना है।",
  },
  "aml.section4.title": {
    en: "Record Keeping",
    ru: "Хранение записей",
    zh: "4. 监控交易",
    ar: "4. مراقبة المعاملات",
    ko: "4. 거래 모니터링",
    fa: "4. نظارت بر تراکنش‌ها",
    ja: "4. 取引の監視",
    fr: "Surveillance des transactions",
    de: "Überwachung von Transaktionen",
    es: "Monitoreo de transacciones",
    it: "Monitoraggio delle transazioni",
    pt: "Monitoramento de transações",
    hi: "4. लेनदेन की निगरानी",
  },
  "aml.section4.content": {
    en: "We maintain all customer and transaction records for a minimum of five years after the end of the business relationship or completion of the transaction.",
    ru: "Мы храним все записи о клиентах и транзакциях в течение минимум пяти лет после окончания деловых отношений или завершения транзакции.",
    zh: "用户不仅通过验证其身份而被了解，还通过分析其交易模式而被了解。Chupapi Munyanya 依靠数据分析作为风险评估和可疑活动检测工具。",
    ar: "يتم التعرف على المستخدمين ليس فقط من خلال التحقق من هويتهم ولكن أيضًا من خلال تحليل أنماط معاملاتهم. تعتمد Chupapi Munyanya على تحليل البيانات كأداة لتقييم المخاطر واكتشاف النشاط المشبوه.",
    ko: "사용자는 신원 확인뿐만 아니라 거래 패턴 분석을 통해서도 알려집니다. Chupapi Munyanya는 위험 평가 및 의심스러운 활동 감지 도구로 데이터 분석에 의존합니다.",
    fa: "کاربران نه تنها با تأیید هویت خود، بلکه با تجزیه و تحلیل الگوهای تراکنش خود نیز شناخته می‌شوند. Chupapi Munyanya برای ارزیابی ریسک و تشخیص فعالیت‌های مشکوک به تجزیه و تحلیل داده‌ها متکی است.",
    ja: "ユーザーは、身元確認だけでなく、取引パターンの分析によっても知られています。Chupapi Munyanyaは、リスク評価と不審な活動検出ツールとしてデータ分析に依存しています。",
    fr: "Les utilisateurs sont connus non seulement en vérifiant leur identité, mais aussi en analysant leurs modèles transactionnels. Chupapi Munyanya s'appuie sur l'analyse des données comme outil d'évaluation des risques et de détection des activités suspectes.",
    de: "Die Benutzer sind nicht nur durch die Überprüfung ihrer Identität bekannt, sondern auch durch die Analyse ihrer Transaktionsmuster. Chupapi Munyanya verlässt sich auf Datenanalyse als Instrument zur Risikobewertung und zur Erkennung verdächtiger Aktivitäten.",
    es: "Los usuarios son conocidos no solo por verificar su identidad, sino también por analizar sus patrones transaccionales. Chupapi Munyanya se basa en el análisis de datos como herramienta de evaluación de riesgos y detección de actividades sospechosas.",
    it: "Gli utenti sono noti non solo verificando la loro identità, ma anche analizzando i loro modelli transazionali. Chupapi Munyanya si affida all'analisi dei dati come strumento di valutazione del rischio e rilevamento di attività sospette.",
    pt: "Os usuários são conhecidos não apenas pela verificação de sua identidade, mas também pela análise de seus padrões transacionais. A Chupapi Munyanya conta com a análise de dados como uma ferramenta de avaliação de risco e detecção de atividades suspeitas.",
    hi: "उपयोगकर्ता न केवल अपनी पहचान के सत्यापन से जाने जाते हैं, बल्कि उनके लेनदेन पैटर्न के विश्लेषण से भी जाने जाते हैं। चुपापी मुन्यान्या जोखिम-मूल्यांकन और संदिग्ध गतिविधि का पता लगाने के उपकरण के रूप में डेटा विश्लेषण पर निर्भर करता है।",
  },
  "aml.section5.title": {
    en: "Employee Training",
    ru: "Обучение сотрудников",
    zh: "5. 风险评估",
    ar: "5. تقييم المخاطر",
    ko: "5. 위험 평가",
    fa: "5. ارزیابی ریسک",
    ja: "5. リスク評価",
    fr: "Évaluation des risques",
    de: "Risikobewertung",
    es: "Evaluación de riesgos",
    it: "Valutazione del rischio",
    pt: "Avaliação de risco",
    hi: "5. जोखिम मूल्यांकन",
  },
  "aml.section5.content": {
    en: "All employees undergo regular training on AML/KYC matters to stay current with the latest regulatory requirements and methods for detecting suspicious activity.",
    ru: "Все сотрудники проходят регулярное обучение по вопросам AML/KYC, чтобы быть в курсе последних нормативных требований и методов выявления подозрительной активности.",
    zh: "Chupapi Munyanya 对其用户及其交易采用基于风险的方法。它对其用户进行全面的风险评估，并根据感知风险对其进行分类。",
    ar: "تطبق Chupapi Munyanya نهجًا قائمًا على المخاطر على مستخدميها ومعاملاتهم. تقوم بإجراء تقييم شامل للمخاطر لمستخدميها وتصنيفهم وفقًا للمخاطر المتصورة.",
    ko: "Chupapi Munyanya는 사용자와 거래에 위험 기반 접근 방식을 적용합니다. 사용자에 대한 종합적인 위험 평가를 수행하고 인식된 위험에 따라 분류합니다.",
    fa: "Chupapi Munyanya رویکردی مبتنی بر ریسک را برای کاربران و تراکنش‌های آنها اعمال می‌کند. این شرکت ارزیابی جامعی از ریسک کاربران خود انجام می‌دهد و آنها را بر اساس ریسک درک شده طبقه‌بندی می‌کند.",
    ja: "Chupapi Munyanyaは、ユーザーとその取引にリスクベースのアプローチを適用しています。ユーザーの包括的なリスク評価を実施し、認識されたリスクに応じて分類しています。",
    fr: "Chupapi Munyanya applique une approche basée sur les risques à ses utilisateurs et à leurs transactions. Elle effectue une évaluation complète des risques de ses utilisateurs et les catégorise en fonction du risque perçu.",
    de: "Chupapi Munyanya wendet einen risikobasierten Ansatz auf seine Benutzer und deren Transaktionen an. Es führt eine umfassende Risikobewertung seiner Benutzer durch und kategorisiert sie entsprechend dem wahrgenommenen Risiko.",
    es: "Chupapi Munyanya aplica un enfoque basado en el riesgo a sus usuarios y sus transacciones. Realiza una evaluación integral de riesgos de sus usuarios y los categoriza según el riesgo percibido.",
    it: "Chupapi Munyanya applica un approccio basato sul rischio ai suoi utenti e alle loro transazioni. Esegue una valutazione completa del rischio dei suoi utenti e li categorizza in base al rischio percepito.",
    pt: "A Chupapi Munyanya aplica uma abordagem baseada em risco aos seus usuários e suas transações. Realiza uma avaliação abrangente de risco de seus usuários e os categoriza de acordo com o risco percebido.",
    hi: "चुपापी मुन्यान्या अपने उपयोगकर्ताओं और उनके लेनदेन के लिए जोखिम-आधारित दृष्टिकोण लागू करता है। यह अपने उपयोगकर्ताओं का व्यापक जोखिम मूल्यांकन करता है और उन्हें अनुभूत जोखिम के अनुसार वर्गीकृत करता है।",
  },
  "aml.section6.title": {
    en: "Reporting Suspicious Activity",
    ru: "Сообщение о подозрительной активности",
    zh: "6. 可疑活动报告",
    ar: "6. الإبلاغ عن النشاط المشبوه",
    ko: "6. 의심스러운 활동 보고",
    fa: "6. گزارش فعالیت مشکوک",
    ja: "6. 不審な活動の報告",
    fr: "Signalement d'activités suspectes",
    de: "Meldung verdächtiger Aktivitäten",
    es: "Informe de actividades sospechosas",
    it: "Segnalazione di attività sospette",
    pt: "Relatório de atividades suspeitas",
    hi: "6. संदिग्ध गतिविधि रिपोर्टिंग",
  },
  "aml.section6.content": {
    en: "We promptly report any suspicious activity to the appropriate regulatory authorities in accordance with applicable law.",
    ru: "Мы незамедлительно сообщаем о любой подозрительной активности соответствующим регулирующим органам в соответствии с применимым законодательством.",
    zh: "Chupapi Munyanya 已制定程序，向相关当局报告可疑活动。合规官负责提交可疑活动报告。",
    ar: "لدى Chupapi Munyanya إجراءات للإبلاغ عن النشاط المشبوه إلى السلطات المختصة. مسؤول الامتثال مسؤول عن تقديم تقارير عن النشاط المشبوه.",
    ko: "Chupapi Munyanya는 관련 당국에 의심스러운 활동을 보고하기 위한 절차를 마련하고 있습니다. 준법 책임자는 의심스러운 활동 보고서 제출을 담당합니다.",
    fa: "Chupapi Munyanya روش‌هایی برای گزارش فعالیت‌های مشکوک به مقامات مربوطه دارد. مسئول انطباق مسئول ارسال گزارش‌های فعالیت مشکوک است.",
    ja: "Chupapi Munyanyaは、関連当局に不審な活動を報告するための手続きを整えています。コンプライアンス責任者は、不審な活動の報告書の提出を担当しています。",
    fr: "Chupapi Munyanya a mis en place des procédures pour signaler les activités suspectes aux autorités compétentes. Le Responsable de la conformité est chargé de déposer des rapports d'activités suspectes.",
    de: "Chupapi Munyanya hat Verfahren eingerichtet, um verdächtige Aktivitäten den zuständigen Behörden zu melden. Der Compliance-Beauftragte ist für die Einreichung von Berichten über verdächtige Aktivitäten verantwortlich.",
    es: "Chupapi Munyanya tiene procedimientos establecidos para informar actividades sospechosas a las autoridades pertinentes. El Oficial de Cumplimiento es responsable de presentar informes de actividades sospechosas.",
    it: "Chupapi Munyanya ha procedure in atto per segnalare attività sospette alle autorità competenti. Il Responsabile della conformità è responsabile della presentazione di segnalazioni di attività sospette.",
    pt: "A Chupapi Munyanya tem procedimentos em vigor para relatar atividades suspeitas às autoridades relevantes. O Oficial de Conformidade é responsável por arquivar relatórios de atividades suspeitas.",
    hi: "चुपापी मुन्यान्या के पास संबंधित अधिकारियों को संदिग्ध गतिविधि की रिपोर्ट करने के लिए प्रक्रियाएं हैं। अनुपालन अधिकारी संदिग्ध गतिविधि की रिपोर्ट दाखिल करने के लिए जिम्मेदार है।",
  },
  "aml.section7.title": {
    en: "Regulatory Compliance",
    ru: "Соответствие нормативным требованиям",
    zh: "7. 记录保存",
    ar: "7. حفظ السجلات",
    ko: "7. 기록 보관",
    fa: "7. نگهداری سوابق",
    ja: "7. 記録の保管",
    fr: "Conservation des documents",
    de: "Aufbewahrung von Aufzeichnungen",
    es: "Mantenimiento de registros",
    it: "Conservazione dei registri",
    pt: "Manutenção de registros",
    hi: "7. रिकॉर्ड रखना",
  },
  "aml.section7.content": {
    en: "We regularly review and update our policies and procedures to ensure compliance with the latest regulatory requirements.",
    ru: "Мы регулярно пересматриваем и обновляем наши политики и процедуры для обеспечения соответствия последним нормативным требованиям.",
    zh: "所有交易和 KYC 文件的记录保存至少五年，或按适用法律和法规的要求保存。",
    ar: "يتم الاحتفاظ بسجلات جميع المعاملات ومستندات اعرف عميلك لمدة لا تقل عن خمس سنوات أو حسب ما تقتضيه القوانين واللوائح المعمول بها.",
    ko: "모든 거래 및 KYC 문서의 기록은 최소 5년 또는 관련 법률 및 규정에서 요구하는 기간 동안 유지됩니다.",
    fa: "سوابق تمام تراکنش‌ها و اسناد KYC حداقل به مدت پنج سال یا طبق الزامات قوانین و مقررات قابل اجرا نگهداری می‌شوند.",
    ja: "すべての取引とKYC文書の記録は、最低5年間、または適用される法律や規制で要求される期間保管されます。",
    fr: "Les enregistrements de toutes les transactions et des documents KYC sont conservés pendant au moins cinq ans ou selon les exigences des lois et réglementations applicables.",
    de: "Aufzeichnungen aller Transaktionen und KYC-Dokumente werden für mindestens fünf Jahre oder gemäß den Anforderungen der geltenden Gesetze und Vorschriften aufbewahrt.",
    es: "Los registros de todas las transacciones y documentos KYC se mantienen durante un mínimo de cinco años o según lo requieran las leyes y regulaciones aplicables.",
    it: "I registri di tutte le transazioni e i documenti KYC sono conservati per un minimo di cinque anni o come richiesto dalle leggi e dai regolamenti applicabili.",
    pt: "Os registros de todas as transações e documentos KYC são mantidos por um mínimo de cinco anos ou conforme exigido pelas leis e regulamentos aplicáveis.",
    hi: "सभी लेनदेन और केवाईसी दस्तावेजों के रिकॉर्ड न्यूनतम पांच वर्षों के लिए या लागू कानूनों और विनियमों द्वारा आवश्यक अनुसार बनाए रखे जाते हैं।",
  },
  "aml.section8.title": {
    en: "Contact Information",
    ru: "Контактная информация",
    zh: "8. 更新和培训",
    ar: "8. التحديثات والتدريب",
    ko: "8. 업데이트 및 교육",
    fa: "8. به‌روزرسانی‌ها و آموزش",
    ja: "8. 更新とトレーニング",
    fr: "Mises à jour et formation",
    de: "Aktualisierungen und Schulungen",
    es: "Actualizaciones y capacitación",
    it: "Aggiornamenti e formazione",
    pt: "Atualizações e treinamento",
    hi: "8. अपडेट और प्रशिक्षण",
  },
  "aml.section8.content": {
    en: "If you have any questions regarding our AML/KYC policy, please contact our compliance department at compliance@chupapi-vpn.com.",
    ru: "Если у вас есть вопросы относительно нашей политики AML/KYC, пожалуйста, свяжитесь с нашим отделом соответствия по адресу compliance@chupapi-vpn.com.",
    zh: "本反洗钱/了解您的客户政策定期审查和更新，以确保符合适用的法律和法规。Chupapi Munyanya 的所有员工都接受有关反洗钱/了解您的客户程序的定期培训。",
    ar: "تتم مراجعة وتحديث سياسة مكافحة غسل الأموال/اعرف عميلك هذه بانتظام لضمان الامتثال للقوانين واللوائح المعمول بها. يخضع جميع موظفي Chupapi Munyanya لتدريب منتظم على إجراءات مكافحة غسل الأموال/اعرف عميلك.",
    ko: "이 자금세탁방지/고객확인제도 정책은 관련 법률 및 규정 준수를 보장하기 위해 정기적으로 검토 및 업데이트됩니다. Chupapi Munyanya의 모든 직원은 자금세탁방지/고객확인제도 절차에 대한 정기적인 교육을 받습니다.",
    fa: "این سیاست مبارزه با پولشویی/شناخت مشتری به طور منظم بررسی و به‌روزرسانی می‌شود تا از انطباق با قوانین و مقررات قابل اجرا اطمینان حاصل شود. تمام کارکنان Chupapi Munyanya آموزش‌های منظمی در مورد روش‌های مبارزه با پولشویی/شناخت مشتری می‌بینند.",
    ja: "このAML/KYCポリシーは、適用される法律や規制への準拠を確保するために定期的に見直しと更新が行われています。Chupapi Munyanyaのすべての従業員は、AML/KYC手続きに関する定期的なトレーニングを受けています。",
    fr: "Cette politique LAB/KYC est régulièrement revue et mise à jour pour assurer la conformité aux lois et réglementations applicables. Tous les employés de Chupapi Munyanya suivent une formation régulière sur les procédures LAB/KYC.",
    de: "Diese AML/KYC-Richtlinie wird regelmäßig überprüft und aktualisiert, um die Einhaltung der geltenden Gesetze und Vorschriften zu gewährleisten. Alle Mitarbeiter von Chupapi Munyanya nehmen regelmäßig an Schulungen zu AML/KYC-Verfahren teil.",
    es: "Esta Política AML/KYC se revisa y actualiza regularmente para garantizar el cumplimiento de las leyes y regulaciones aplicables. Todos los empleados de Chupapi Munyanya reciben capacitación regular sobre los procedimientos AML/KYC.",
    it: "Questa Politica AML/KYC viene regolarmente rivista e aggiornata per garantire la conformità alle leggi e ai regolamenti applicabili. Tutti i dipendenti di Chupapi Munyanya seguono una formazione regolare sulle procedure AML/KYC.",
    pt: "Esta Política AML/KYC é regularmente revisada e atualizada para garantir a conformidade com as leis e regulamentos aplicáveis. Todos os funcionários da Chupapi Munyanya passam por treinamento regular sobre procedimentos AML/KYC.",
    hi: "यह एएमएल/केवाईसी नीति लागू कानूनों और विनियमों के अनुपालन को सुनिश्चित करने के लिए नियमित रूप से समीक्षा और अपडेट की जाती है। चुपापी मुन्यान्या के सभी कर्मचारी एएमएल/केवाईसी प्रक्रियाओं पर नियमित प्रशिक्षण से गुजरते हैं।",
  },
  "header.home": {
    en: "Home",
    ru: "Главная",
    zh: "首页",
    ar: "الرئيسية",
    ko: "홈",
    fa: "خانه",
    ja: "ホーム",
    fr: "Accueil",
    de: "Startseite",
    es: "Inicio",
    it: "Home",
    pt: "Início",
    hi: "होम",
  },
  "hero.title1": {
    en: "Secure",
    ru: "Безопасный",
    zh: "安全的",
    ar: "آمن",
    ko: "안전한",
    fa: "امن",
    ja: "安全な",
    fr: "Sécurisé",
    de: "Sicheres",
    es: "Seguro",
    it: "Sicuro",
    pt: "Seguro",
    hi: "सुरक्षित",
  },
  "hero.title2": {
    en: "Internet",
    ru: "интернет",
    zh: "互联网",
    ar: "إنترنت",
    ko: "인터넷",
    fa: "اینترنت",
    ja: "インターネット",
    fr: "Internet",
    de: "Internet",
    es: "Internet",
    it: "Internet",
    pt: "Internet",
    hi: "इंटरनेट",
  },
  "hero.subtitle": {
    en: "Advanced protection based on VLESS and Shadowsocks technologies for your privacy",
    ru: "Продвинутая защита на основе технологий VLESS и Shadowsocks для вашей конфиденциальности",
    zh: "基于 VLESS 和 Shadowsocks 技术的高级保护，保障您的隐私",
    ar: "حماية متقدمة تعتمد على تقنيات VLESS و Shadowsocks لخصوصيتك",
    ko: "VLESS 및 Shadowsocks 기술을 기반으로 한 개인 정보 보호를 위한 고급 보호",
    fa: "محافظت پیشرفته بر اساس فناوری‌های VLESS و Shadowsocks برای حفظ حریم خصوصی شما",
    ja: "VLESS と Shadowsocks テクノロジーに基づくプライバシーのための高度な保護",
    fr: "Protection avancée basée sur les technologies VLESS et Shadowsocks pour votre confidentialité",
    de: "Fortschrittlicher Schutz basierend auf VLESS- und Shadowsocks-Technologien für Ihre Privatsphäre",
    es: "Protección avanzada basada en tecnologías VLESS y Shadowsocks para su privacidad",
    it: "Protezione avanzata basata sulle tecnologie VLESS e Shadowsocks per la tua privacy",
    pt: "Proteção avançada baseada nas tecnologias VLESS e Shadowsocks para sua privacidade",
    hi: "आपकी गोपनीयता के लिए VLESS और Shadowsocks तकनीकों पर आधारित उन्नत सुरक्षा",
  },
  "hero.feature2": {
    en: "High-Speed Servers",
    ru: "Высокоскоростные серверы",
    zh: "高速服务器",
    ar: "خوادم عالية السرعة",
    ko: "고속 서버",
    fa: "سرورهای پرسرعت",
    ja: "高速サーバー",
    fr: "Serveurs haute vitesse",
    de: "Hochgeschwindigkeitsserver",
    es: "Servidores de alta velocidad",
    it: "Server ad alta velocità",
    pt: "Servidores de alta velocidade",
    hi: "उच्च-गति सर्वर",
  },
  "hero.feature3": {
    en: "256-bit Encryption",
    ru: "256-битное шифрование",
    zh: "256 位加密",
    ar: "تشفير 256 بت",
    ko: "256비트 암호화",
    fa: "رمزگذاری 256 بیتی",
    ja: "256ビット暗号化",
    fr: "Chiffrement 256 bits",
    de: "256-Bit-Verschlüsselung",
    es: "Cifrado de 256 bits",
    it: "Crittografia a 256 bit",
    pt: "Criptografia de 256 bits",
    hi: "256-बिट एन्क्रिप्शन",
  },
  "hero.feature4": {
    en: "Secure and stable connection",
    ru: "Безопасное и стабильное соединение",
    zh: "安全稳定的连接",
    ar: "اتصال آمن ومستقر",
    ko: "안전하고 안정적인 연결",
    fa: "اتصال امن و پایدار",
    ja: "安全で安定した接続",
    fr: "Connexion sécurisée et stable",
    de: "Sichere und stabile Verbindung",
    es: "Conexión segura y estable",
    it: "Connessione sicura e stabile",
    pt: "Conexão segura e estável",
    hi: "सुरक्षित और स्थिर कनेक्शन",
  },
  "download.title1": {
    en: "Download our",
    ru: "Скачайте наши",
    zh: "下载我们的",
    ar: "تحميل",
    ko: "다운로드",
    fa: "دانلود",
    ja: "ダウンロード",
    fr: "Téléchargez nos",
    de: "Laden Sie unsere",
    es: "Descarga nuestras",
    it: "Scarica le nostre",
    pt: "Baixe nossos",
    hi: "हमारे ऐप्स डाउनलोड करें",
  },
  "download.title2": {
    en: "apps",
    ru: "приложения",
    zh: "应用程序",
    ar: "تطبيقاتنا",
    ko: "앱",
    fa: "اپلیکیشن های ما",
    ja: "アプリ",
    fr: "applications",
    de: "Apps",
    es: "aplicaciones",
    it: "app",
    pt: "aplicativos",
    hi: "ऐप्स",
  },
  "download.subtitle": {
    en: "Protect your connection on any device with our user-friendly applications",
    ru: "Защитите ваше соединение на любом устройстве с нашими удобными приложениями",
    zh: "使用我们用户友好的应用程序保护您在任何设备上的连接",
    ar: "احمِ اتصالك على أي جهاز باستخدام تطبيقاتنا سهلة الاستخدام",
    ko: "사용자 친화적인 애플리케이션으로 모든 기기에서 연결을 보호하세요",
    fa: "با استفاده از برنامه‌های کاربرپسند ما، اتصال خود را در هر دستگاهی محافظت کنید",
    ja: "ユーザーフレンドリーなアプリケーションで、あらゆるデバイスでの接続を保護します",
    fr: "Protégez votre connexion sur n'importe quel appareil avec nos applications conviviales",
    de: "Schützen Sie Ihre Verbindung auf jedem Gerät mit unseren benutzerfreundlichen Anwendungen",
    es: "Proteja su conexión en cualquier dispositivo con nuestras aplicaciones fáciles de usar",
    it: "Proteggi la tua connessione su qualsiasi dispositivo con le nostre applicazioni facili da usare",
    pt: "Proteja sua conexão em qualquer dispositivo com nossos aplicativos fáceis de usar",
    hi: "हमारे उपयोगकर्ता-अनुकूल एप्लिकेशन के साथ किसी भी डिवाइस पर अपने कनेक्शन की सुरक्षा करें",
  },
  "platform.ios": {
    en: "iOS",
    ru: "iOS",
    zh: "iOS",
    ar: "iOS",
    ko: "iOS",
    fa: "iOS",
    ja: "iOS",
    fr: "iOS",
    de: "iOS",
    es: "iOS",
    it: "iOS",
    pt: "iOS",
    hi: "iOS",
  },
  "platform.ios.desc": {
    en: "Secure browsing on iPhone and iPad with our convenient app",
    ru: "Безопасный просмотр на iPhone и iPad с нашим удобным приложением",
    zh: "使用我们便捷的应用程序在 iPhone 和 iPad 上安全浏览",
    ar: "تصفح آمن على iPhone و iPad مع تطبيقنا المريح",
    ko: "편리한 앱으로 iPhone 및 iPad에서 안전한 브라우징",
    fa: "مرور امن در آیفون و آیپد با برنامه راحت ما",
    ja: "便利なアプリでiPhoneとiPadの安全なブラウジング",
    fr: "Navigation sécurisée sur iPhone et iPad avec notre application pratique",
    de: "Sicheres Surfen auf iPhone und iPad mit unserer praktischen App",
    es: "Navegación segura en iPhone y iPad con nuestra cómoda aplicación",
    it: "Navigazione sicura su iPhone e iPad con la nostra app conveniente",
    pt: "Navegação segura no iPhone e iPad com nosso aplicativo conveniente",
    hi: "हमारे सुविधाजनक ऐप के साथ iPhone और iPad पर सुरक्षित ब्राउज़िंग",
  },
  "platform.android": {
    en: "Android",
    ru: "Android",
    zh: "Android",
    ar: "Android",
    ko: "Android",
    fa: "Android",
    ja: "Android",
    fr: "Android",
    de: "Android",
    es: "Android",
    it: "Android",
    pt: "Android",
    hi: "Android",
  },
  "platform.android.desc": {
    en: "Protection for your Android devices with our feature-rich application",
    ru: "Защита для ваших Android устройств с нашим многофункциональным приложением",
    zh: "使用我们功能丰富的应用程序保护您的 Android 设备",
    ar: "حماية لأجهزة Android الخاصة بك مع تطبيقنا الغني بالميزات",
    ko: "다양한 기능을 갖춘 애플리케이션으로 Android 기기 보호",
    fa: "محافظت از دستگاه‌های Android شما با برنامه پر امکانات ما",
    ja: "機能豊富なアプリケーションでAndroidデバイスを保護",
    fr: "Protection pour vos appareils Android avec notre application riche en fonctionnalités",
    de: "Schutz für Ihre Android-Geräte mit unserer funktionsreichen Anwendung",
    es: "Protección para sus dispositivos Android con nuestra aplicación rica en funciones",
    it: "Protezione per i tuoi dispositivi Android con la nostra applicazione ricca di funzionalità",
    pt: "Proteção para seus dispositivos Android com nosso aplicativo rico em recursos",
    hi: "हमारे फीचर-रिच एप्लिकेशन के साथ आपके Android डिवाइस के लिए सुरक्षा",
  },
  "platform.windows": {
    en: "Windows",
    ru: "Windows",
    zh: "Windows",
    ar: "Windows",
    ko: "Windows",
    fa: "Windows",
    ja: "Windows",
    fr: "Windows",
    de: "Windows",
    es: "Windows",
    it: "Windows",
    pt: "Windows",
    hi: "Windows",
  },
  "platform.windows.desc": {
    en: "Coming soon for Windows PC with advanced security features",
    ru: "Скоро для Windows PC с продвинутыми функциями безопасности",
    zh: "即将为 Windows PC 提供高级安全功能",
    ar: "قريبًا لأجهزة كمبيوتر Windows مع ميزات أمان متقدمة",
    ko: "고급 보안 기능을 갖춘 Windows PC용 출시 예정",
    fa: "به زودی برای کامپیوترهای ویندوز با ویژگی‌های امنیتی پیشرفته",
    ja: "高度なセキュリティ機能を備えたWindows PC向けに近日公開",
    fr: "Bientôt disponible pour PC Windows avec des fonctionnalités de sécurité avancées",
    de: "Demnächst für Windows-PC mit erweiterten Sicherheitsfunktionen",
    es: "Próximamente para PC con Windows con funciones de seguridad avanzadas",
    it: "In arrivo per PC Windows con funzionalità di sicurezza avanzate",
    pt: "Em breve para PC Windows com recursos avançados de segurança",
    hi: "उन्नत सुरक्षा सुविधाओं के साथ Windows PC के लिए जल्द आ रहा है",
  },
  "platform.macos": {
    en: "macOS",
    ru: "macOS",
    zh: "macOS",
    ar: "macOS",
    ko: "macOS",
    fa: "macOS",
    ja: "macOS",
    fr: "macOS",
    de: "macOS",
    es: "macOS",
    it: "macOS",
    pt: "macOS",
    hi: "macOS",
  },
  "platform.macos.desc": {
    en: "Coming soon for Mac computers with seamless integration",
    ru: "Скоро для Mac компьютеров с бесшовной интеграцией",
    zh: "即将为 Mac 电脑提供无缝集成",
    ar: "قريبًا لأجهزة كمبيوتر Mac مع تكامل سلس",
    ko: "원활한 통합을 갖춘 Mac 컴퓨터용 출시 예정",
    fa: "به زودی برای کامپیوترهای مک با ادغام یکپارچه",
    ja: "シームレスな統合を備えたMacコンピュータ向けに近日公開",
    fr: "Bientôt disponible pour les ordinateurs Mac avec une intégration transparente",
    de: "Demnächst für Mac-Computer mit nahtloser Integration",
    es: "Próximamente para computadoras Mac con integración perfecta",
    it: "In arrivo per computer Mac con integrazione perfetta",
    pt: "Em breve para computadores Mac com integração perfeita",
    hi: "सहज एकीकरण के साथ Mac कंप्यूटर के लिए जल्द आ रहा है",
  },
  "platform.linux": {
    en: "Linux",
    ru: "Linux",
    zh: "Linux",
    ar: "Linux",
    ko: "Linux",
    fa: "Linux",
    ja: "Linux",
    fr: "Linux",
    de: "Linux",
    es: "Linux",
    it: "Linux",
    pt: "Linux",
    hi: "Linux",
  },
  "platform.linux.desc": {
    en: "Coming soon for Linux systems with open-source compatibility",
    ru: "Скоро для Linux систем с совместимостью с открытым исходным кодом",
    zh: "即将为 Linux 系统提供开源兼容性",
    ar: "قريبًا لأنظمة Linux مع توافق المصدر المفتوح",
    ko: "오픈 소스 호환성을 갖춘 Linux 시스템용 출시 예정",
    fa: "به زودی برای سیستم‌های لینوکس با سازگاری متن باز",
    ja: "オープンソース互換性を備えたLinuxシステム向けに近日公開",
    fr: "Bientôt disponible pour les systèmes Linux avec compatibilité open-source",
    de: "Demnächst für Linux-Systeme mit Open-Source-Kompatibilität",
    es: "Próximamente para sistemas Linux con compatibilidad de código abierto",
    it: "In arrivo per sistemi Linux con compatibilità open-source",
    pt: "Em breve para sistemas Linux com compatibilidade de código aberto",
    hi: "ओपन-सोर्स संगतता के साथ Linux सिस्टम के लिए जल्द आ रहा है",
  },
  "platform.router": {
    en: "Router",
    ru: "Роутер",
    zh: "路由器",
    ar: "جهاز التوجيه",
    ko: "라우터",
    fa: "روتر",
    ja: "ルーター",
    fr: "Routeur",
    de: "Router",
    es: "Router",
    it: "Router",
    pt: "Roteador",
    hi: "राउटर",
  },
  "platform.router.desc": {
    en: "Coming soon for routers to protect your entire home network",
    ru: "Скоро для роутеров для защиты всей домашней сети",
    zh: "即将为路由器提供保护整个家庭网络的功能",
    ar: "قريبًا لأجهزة التوجيه لحماية شبكة منزلك بالكامل",
    ko: "전체 홈 네트워크를 보호하기 위한 라우터용 출시 예정",
    fa: "به زودی برای روترها برای محافظت از کل شبکه خانگی شما",
    ja: "ホームネットワーク全体を保護するルーター向けに近日公開",
    fr: "Bientôt disponible pour les routeurs afin de protéger l'ensemble de votre réseau domestique",
    de: "Demnächst für Router zum Schutz Ihres gesamten Heimnetzwerks",
    es: "Próximamente para routers para proteger toda su red doméstica",
    it: "In arrivo per router per proteggere l'intera rete domestica",
    pt: "Em breve para roteadores para proteger toda a sua rede doméstica",
    hi: "आपके पूरे होम नेटवर्क की सुरक्षा के लिए राउटर के लिए जल्द आ रहा है",
  },
  "coming.soon": {
    en: "Coming Soon",
    ru: "Скоро",
    zh: "即将推出",
    ar: "قريبًا",
    ko: "곧 출시",
    fa: "به زودی",
    ja: "近日公開",
    fr: "Bientôt disponible",
    de: "Demnächst",
    es: "Próximamente",
    it: "Prossimamente",
    pt: "Em breve",
    hi: "जल्द आ रहा है",
  },
  "footer.legal": {
    en: "Legal Information",
    ru: "Юридическая информация",
    zh: "法律信息",
    ar: "المعلومات القانونية",
    ko: "법적 정보",
    fa: "اطلاعات حقوقی",
    ja: "法的情報",
    fr: "Informations légales",
    de: "Rechtliche Informationen",
    es: "Información legal",
    it: "Informazioni legali",
    pt: "Informações legais",
    hi: "कानूनी जानकारी",
  },
  "footer.aml": {
    en: "AML/KYC Policy",
    ru: "Политика AML/KYC",
    zh: "反洗钱/了解您的客户政策",
    ar: "سياسة مكافحة غسل الأموال/اعرف عميلك",
    ko: "자금세탁방지/고객확인제도 정책",
    fa: "سیاست مبارزه با پولشویی/شناخت مشتری",
    ja: "マネーロンダリング防止/顧客確認ポリシー",
    fr: "Politique LAB/KYC",
    de: "AML/KYC-Richtlinie",
    es: "Política AML/KYC",
    it: "Politica AML/KYC",
    pt: "Política AML/KYC",
    hi: "एएमएल/केवाईसी नीति",
  },
  "footer.support": {
    en: "Support",
    ru: "Поддержка",
    zh: "支持",
    ar: "الدعم",
    ko: "지원",
    fa: "پشتیبانی",
    ja: "サポート",
    fr: "Support",
    de: "Unterstützung",
    es: "Soporte",
    it: "Supporto",
    pt: "Suporte",
    hi: "सहायता",
  },
  "footer.faq": {
    en: "FAQ (coming soon)",
    ru: "FAQ (скоро)",
    zh: "常见问题（即将推出）",
    ar: "الأسئلة الشائعة (قريبًا)",
    ko: "FAQ (곧 출시)",
    fa: "سوالات متداول (به زودی)",
    ja: "FAQ（近日公開）",
    fr: "FAQ (bientôt disponible)",
    de: "FAQ (demnächst)",
    es: "FAQ (próximamente)",
    it: "FAQ (prossimamente)",
    pt: "FAQ (em breve)",
    hi: "अक्सर पूछे जाने वाले प्रश्न (जल्द आ रहा है)",
  },
  "footer.guide": {
    en: "Installation Guide (coming soon)",
    ru: "Руководство по установке (скоро)",
    zh: "安装指南（即将推出）",
    ar: "دليل التثبيت (قريبًا)",
    ko: "설치 가이드 (곧 출시)",
    fa: "راهنمای نصب (به زودی)",
    ja: "インストールガイド（近日公開）",
    fr: "Guide d'installation (bientôt disponible)",
    de: "Installationsanleitung (demnächst)",
    es: "Guía de instalación (próximamente)",
    it: "Guida all'installazione (prossimamente)",
    pt: "Guia de instalação (em breve)",
    hi: "इंस्टॉलेशन गाइड (जल्द आ रहा है)",
  },
  "footer.contact": {
    en: "Contact Us",
    ru: "Связаться с нами",
    zh: "联系我们",
    ar: "اتصل بنا",
    ko: "문의하기",
    fa: "تماس با ما",
    ja: "お問い合わせ",
    fr: "Contactez-nous",
    de: "Kontaktieren Sie uns",
    es: "Contáctenos",
    it: "Contattaci",
    pt: "Contate-nos",
    hi: "संपर्क करें",
  },
  "footer.email": {
    en: "Email: support@chpnvpn.com",
    ru: "Email: support@chpnvpn.com",
    zh: "电子邮件: support@chpnvpn.com",
    ar: "البريد الإلكتروني: support@chpnvpn.com",
    ko: "이메일: support@chpnvpn.com",
    fa: "ایمیل: support@chpnvpn.com",
    ja: "メール: support@chpnvpn.com",
    fr: "Email: support@chpnvpn.com",
    de: "E-Mail: support@chpnvpn.com",
    es: "Correo electrónico: support@chpnvpn.com",
    it: "Email: support@chpnvpn.com",
    pt: "Email: support@chpnvpn.com",
    hi: "ईमेल: support@chpnvpn.com",
  },
  "footer.telegram": {
    en: "Telegram: t.me/chpnvpn",
    ru: "Telegram: t.me/chpnvpn",
    zh: "Telegram: t.me/chpnvpn",
    ar: "تيليجرام: t.me/chpnvpn",
    ko: "텔레그램: t.me/chpnvpn",
    fa: "تلگرام: t.me/chpnvpn",
    ja: "Telegram: t.me/chpnvpn",
    fr: "Telegram: t.me/chpnvpn",
    de: "Telegram: t.me/chpnvpn",
    es: "Telegram: t.me/chpnvpn",
    it: "Telegram: t.me/chpnvpn",
    pt: "Telegram: t.me/chpnvpn",
    hi: "टेलीग्राम: t.me/chpnvpn",
  },
  "footer.payment": {
    en: "Payment Methods",
    ru: "Способы оплаты",
    zh: "支付方式",
    ar: "طرق الدفع",
    ko: "결제 방법",
    fa: "روش‌های پرداخت",
    ja: "お支払い方法",
    fr: "Méthodes de paiement",
    de: "Zahlungsmethoden",
    es: "Métodos de pago",
    it: "Metodi di pagamento",
    pt: "Métodos de pagamento",
    hi: "भुगतान के तरीके",
  },
  "language.select": {
    en: "Select language",
    ru: "Выбрать язык",
    zh: "选择语言",
    ar: "اختر اللغة",
    ko: "언어 선택",
    fa: "انتخاب زبان",
    ja: "言語を選択",
    fr: "Sélectionner la langue",
    de: "Sprache auswählen",
    es: "Seleccionar idioma",
    it: "Seleziona lingua",
    pt: "Selecionar idioma",
    hi: "भाषा चुनें",
  },
  // Добавляем переводы для тарифов
  "pricing.title": {
    en: "Choose Your Plan",
    ru: "Выберите тарифный план",
    zh: "选择您的套餐",
    ar: "اختر خطتك",
    ko: "요금제 선택",
    fa: "طرح خود را انتخاب کنید",
    ja: "プランを選択",
    fr: "Choisissez votre forfait",
    de: "Wählen Sie Ihren Tarif",
    es: "Elija su plan",
    it: "Scegli il tuo piano",
    pt: "Escolha seu plano",
    hi: "अपना प्लान चुनें",
  },
  "pricing.subtitle": {
    en: "We offer flexible pricing options to meet your needs",
    ru: "Мы предлагаем гибкие варианты тарифов для удовлетворения ваших потребностей",
    zh: "我们提供灵活的定价选项以满足您的需求",
    ar: "نقدم خيارات تسعير مرنة لتلبية احتياجاتك",
    ko: "귀하의 요구를 충족하는 유연한 가격 옵션을 제공합니다",
    fa: "ما گزینه‌های قیمت‌گذاری انعطاف‌پذیری را برای برآورده کردن نیازهای شما ارائه می‌دهیم",
    ja: "あなたのニーズに合わせた柔軟な価格オプションを提供しています",
    fr: "Nous proposons des options de tarification flexibles pour répondre à vos besoins",
    de: "Wir bieten flexible Preisoptionen, um Ihren Bedürfnissen gerecht zu werden",
    es: "Ofrecemos opciones de precios flexibles para satisfacer sus necesidades",
    it: "Offriamo opzioni di prezzo flessibili per soddisfare le tue esigenze",
    pt: "Oferecemos opções de preços flexíveis para atender às suas necessidades",
    hi: "हम आपकी जरूरतों को पूरा करने के लिए लचीले मूल्य निर्धारण विकल्प प्रदान करते हैं",
  },
  "pricing.popular": {
    en: "Most Popular",
    ru: "Самый популярный",
    zh: "最受欢迎",
    ar: "الأكثر شعبية",
    ko: "가장 인기 있는",
    fa: "محبوب‌ترین",
    ja: "最も人気",
    fr: "Le plus populaire",
    de: "Am beliebtesten",
    es: "Más popular",
    it: "Più popolare",
    pt: "Mais popular",
    hi: "सबसे लोकप्रिय",
  },
  "pricing.monthly": {
    en: "month",
    ru: "месяц",
    zh: "月",
    ar: "شهر",
    ko: "월",
    fa: "ماه",
    ja: "月",
    fr: "mois",
    de: "Monat",
    es: "mes",
    it: "mese",
    pt: "mês",
    hi: "महीना",
  },
  "pricing.perMonth": {
    en: "per month",
    ru: "в месяц",
    zh: "每月",
    ar: "في الشهر",
    ko: "월별",
    fa: "در ماه",
    ja: "月額",
    fr: "par mois",
    de: "pro Monat",
    es: "por mes",
    it: "al mese",
    pt: "por mês",
    hi: "प्रति माह",
  },
  "pricing.months": {
    en: "months",
    ru: "месяцев",
    zh: "个月",
    ar: "أشهر",
    ko: "개월",
    fa: "ماه",
    ja: "ヶ月",
    fr: "mois",
    de: "Monate",
    es: "meses",
    it: "mesi",
    pt: "meses",
    hi: "महीने",
  },
  "pricing.gift": {
    en: "free",
    ru: "в подарок",
    zh: "免费",
    ar: "مجانًا",
    ko: "무료",
    fa: "رایگان",
    ja: "無料",
    fr: "gratuit",
    de: "gratis",
    es: "gratis",
    it: "gratuito",
    pt: "grátis",
    hi: "मुफ्त",
  },
  "pricing.discount": {
    en: "Discount",
    ru: "Скидка",
    zh: "折扣",
    ar: "خصم",
    ko: "할인",
    fa: "تخفیف",
    ja: "割引",
    fr: "Remise",
    de: "Rabatt",
    es: "Descuento",
    it: "Sconto",
    pt: "Desconto",
    hi: "छूट",
  },
  "pricing.features.devices": {
    en: "Connect up to 5 devices",
    ru: "Подключение до 5 устройств",
    zh: "连接最多 5 台设备",
    ar: "توصيل ما يصل إلى 5 أجهزة",
    ko: "최대 5대의 기기 연결",
    fa: "اتصال تا 5 دستگاه",
    ja: "最大5台のデバイスを接続",
    fr: "Connectez jusqu'à 5 appareils",
    de: "Verbinden Sie bis zu 5 Geräte",
    es: "Conecte hasta 5 dispositivos",
    it: "Connetti fino a 5 dispositivi",
    pt: "Conecte até 5 dispositivos",
    hi: "5 तक डिवाइस कनेक्ट करें",
  },
  "pricing.features.unlimited": {
    en: "Unlimited bandwidth",
    ru: "Безлимитный трафик",
    zh: "无限带宽",
    ar: "عرض نطاق غير محدود",
    ko: "무제한 대역폭",
    fa: "پهنای باند نامحدود",
    ja: "無制限の帯域幅",
    fr: "Bande passante illimitée",
    de: "Unbegrenzte Bandbreite",
    es: "Ancho de banda ilimitado",
    it: "Larghezza di banda illimitata",
    pt: "Largura de banda ilimitada",
    hi: "असीमित बैंडविड्थ",
  },
  "pricing.features.speed": {
    en: "High-speed connection",
    ru: "Высокоскоростное соединение",
    zh: "高速连接",
    ar: "اتصال عالي السرعة",
    ko: "고속 연결",
    fa: "اتصال پرسرعت",
    ja: "高速接続",
    fr: "Connexion haut débit",
    de: "Hochgeschwindigkeitsverbindung",
    es: "Conexión de alta velocidad",
    it: "Connessione ad alta velocità",
    pt: "Conexão de alta velocidade",
    hi: "हाई-स्पीड कनेक्शन",
  },
  "pricing.features.support": {
    en: "24/7 technical support",
    ru: "Техническая поддержка 24/7",
    zh: "24/7 技术支持",
    ar: "دعم فني على مدار الساعة",
    ko: "24/7 기술 지원",
    fa: "پشتیبانی فنی 24/7",
    ja: "24時間年中無休のテクニカルサポート",
    fr: "Support technique 24/7",
    de: "24/7 technischer Support",
    es: "Soporte técnico 24/7",
    it: "Supporto tecnico 24/7",
    pt: "Suporte técnico 24/7",
    hi: "24/7 तकनीकी सहायता",
  },
  "pricing.button": {
    en: "Subscribe",
    ru: "Подписаться",
    zh: "订阅",
    ar: "اشترك",
    ko: "구독하기",
    fa: "اشتراک",
    ja: "購読する",
    fr: "S'abonner",
    de: "Abonnieren",
    es: "Suscribirse",
    it: "Abbonati",
    pt: "Assinar",
    hi: "सदस्यता लें",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && languages.some((lang) => lang.code === savedLanguage)) {
      setLanguageState(savedLanguage)
      // Устанавливаем направление текста для RTL языков
      document.documentElement.dir = languages.find((lang) => lang.code === savedLanguage)?.direction || "ltr"
    } else {
      // Определяем язык браузера
      const browserLang = navigator.language.split("-")[0] as Language
      const supportedLang = languages.find((lang) => lang.code === browserLang)
      if (supportedLang) {
        setLanguageState(supportedLang.code)
        document.documentElement.dir = supportedLang.direction
      }
    }
  }, [])

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    if (mounted) {
      localStorage.setItem("language", newLanguage)
      // Устанавливаем направление текста для RTL языков
      const langInfo = languages.find((lang) => lang.code === newLanguage)
      if (langInfo) {
        document.documentElement.dir = langInfo.direction
      }
    }
  }

  const t = (key: string): string => {
    const translation = translations[key]
    if (!translation) return key
    return translation[language] || translation.en || key
  }

  const getLanguageInfo = (code: Language): LanguageInfo => {
    return languages.find((lang) => lang.code === code) || languages[0]
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageInfo, languages }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
